server:
  port: 8080

spring:
  application:
    name: Media-Gallery

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/gallery
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

storage:
  local:
    upload-dir: uploads

jwt:
  secret: ${JWT_SECRET:dGhpc0lzQWJhc2U2NFNhZmVTZWNyZXRLZXkxMjM=====================}
  expiration: ${JWT_EXPIRATION:3000000}


